/********************************************************************
* MCDimuonRecoDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error MCDimuonRecoDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMCDimuonRecoDict();
extern void G__cpp_setup_inheritanceMCDimuonRecoDict();
extern void G__cpp_setup_typetableMCDimuonRecoDict();
extern void G__cpp_setup_memvarMCDimuonRecoDict();
extern void G__cpp_setup_globalMCDimuonRecoDict();
extern void G__cpp_setup_memfuncMCDimuonRecoDict();
extern void G__cpp_setup_funcMCDimuonRecoDict();
extern void G__set_cpp_environmentMCDimuonRecoDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MCDimuonReco.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MCDimuonRecoDictLN_TClass;
extern G__linked_taginfo G__MCDimuonRecoDictLN_TBuffer;
extern G__linked_taginfo G__MCDimuonRecoDictLN_TMemberInspector;
extern G__linked_taginfo G__MCDimuonRecoDictLN_TObject;
extern G__linked_taginfo G__MCDimuonRecoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MCDimuonRecoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MCDimuonRecoDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__MCDimuonRecoDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MCDimuonRecoDictLN_TreeHandler;
extern G__linked_taginfo G__MCDimuonRecoDictLN_MCDimuonReco;

/* STUB derived class for protected member access */
