//
// File generated by rootcint at Fri Jan 16 18:16:49 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME MCParticleFinderDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "MCParticleFinderDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void MCParticleFinder_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_MCParticleFinder(void *p);
   static void deleteArray_MCParticleFinder(void *p);
   static void destruct_MCParticleFinder(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::MCParticleFinder*)
   {
      ::MCParticleFinder *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::MCParticleFinder >(0);
      static ::ROOT::TGenericClassInfo 
         instance("MCParticleFinder", ::MCParticleFinder::Class_Version(), "./MCParticleFinder.h", 8,
                  typeid(::MCParticleFinder), DefineBehavior(ptr, ptr),
                  &::MCParticleFinder::Dictionary, isa_proxy, 4,
                  sizeof(::MCParticleFinder) );
      instance.SetDelete(&delete_MCParticleFinder);
      instance.SetDeleteArray(&deleteArray_MCParticleFinder);
      instance.SetDestructor(&destruct_MCParticleFinder);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::MCParticleFinder*)
   {
      return GenerateInitInstanceLocal((::MCParticleFinder*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::MCParticleFinder*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *MCParticleFinder::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *MCParticleFinder::Class_Name()
{
   return "MCParticleFinder";
}

//______________________________________________________________________________
const char *MCParticleFinder::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::MCParticleFinder*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int MCParticleFinder::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::MCParticleFinder*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void MCParticleFinder::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::MCParticleFinder*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *MCParticleFinder::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::MCParticleFinder*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void MCParticleFinder::Streamer(TBuffer &R__b)
{
   // Stream an object of class MCParticleFinder.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(MCParticleFinder::Class(),this);
   } else {
      R__b.WriteClassBuffer(MCParticleFinder::Class(),this);
   }
}

//______________________________________________________________________________
void MCParticleFinder::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class MCParticleFinder.
      TClass *R__cl = ::MCParticleFinder::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fnsig", &fnsig);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_MCParticleFinder(void *p) {
      delete ((::MCParticleFinder*)p);
   }
   static void deleteArray_MCParticleFinder(void *p) {
      delete [] ((::MCParticleFinder*)p);
   }
   static void destruct_MCParticleFinder(void *p) {
      typedef ::MCParticleFinder current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::MCParticleFinder

/********************************************************
* MCParticleFinderDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableMCParticleFinderDict();

extern "C" void G__set_cpp_environmentMCParticleFinderDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("MCParticleFinder.h");
  G__cpp_reset_tagtableMCParticleFinderDict();
}
#include <new>
extern "C" int G__cpp_dllrevMCParticleFinderDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* MCParticleFinder */
static int G__MCParticleFinderDict_496_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   MCParticleFinder* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new MCParticleFinder(*(TreeHandler*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) MCParticleFinder(*(TreeHandler*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__MCParticleFinderDictLN_MCParticleFinder));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticleFinderDict_496_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((MCParticleFinder*) G__getstructoffset())->getMatchedMCId((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticleFinderDict_496_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MCParticleFinder*) G__getstructoffset())->setNSig((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticleFinderDict_496_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) MCParticleFinder::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticleFinderDict_496_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MCParticleFinder::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticleFinderDict_496_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) MCParticleFinder::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticleFinderDict_496_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      MCParticleFinder::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticleFinderDict_496_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MCParticleFinder*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticleFinderDict_496_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MCParticleFinder::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticleFinderDict_496_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) MCParticleFinder::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticleFinderDict_496_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MCParticleFinder::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticleFinderDict_496_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) MCParticleFinder::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__MCParticleFinderDict_496_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   MCParticleFinder* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new MCParticleFinder(*(MCParticleFinder*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__MCParticleFinderDictLN_MCParticleFinder));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef MCParticleFinder G__TMCParticleFinder;
static int G__MCParticleFinderDict_496_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (MCParticleFinder*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((MCParticleFinder*) (soff+(sizeof(MCParticleFinder)*i)))->~G__TMCParticleFinder();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (MCParticleFinder*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((MCParticleFinder*) (soff))->~G__TMCParticleFinder();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* MCParticleFinder */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncMCParticleFinderDict {
 public:
  G__Sizep2memfuncMCParticleFinderDict(): p(&G__Sizep2memfuncMCParticleFinderDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncMCParticleFinderDict::*p)();
};

size_t G__get_sizep2memfuncMCParticleFinderDict()
{
  G__Sizep2memfuncMCParticleFinderDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceMCParticleFinderDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__MCParticleFinderDictLN_MCParticleFinder))) {
     MCParticleFinder *G__Lderived;
     G__Lderived=(MCParticleFinder*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__MCParticleFinderDictLN_MCParticleFinder),G__get_linked_tagnum(&G__MCParticleFinderDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableMCParticleFinderDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__MCParticleFinderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__MCParticleFinderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MCParticleFinderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__MCParticleFinderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MCParticleFinderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__MCParticleFinderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__MCParticleFinderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MCParticleFinderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__MCParticleFinderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MCParticleFinderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__MCParticleFinderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__MCParticleFinderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__MCParticleFinderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__MCParticleFinderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__MCParticleFinderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__MCParticleFinderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__MCParticleFinderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__MCParticleFinderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__MCParticleFinderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* MCParticleFinder */
static void G__setup_memvarMCParticleFinder(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__MCParticleFinderDictLN_MCParticleFinder));
   { MCParticleFinder *p; p=(MCParticleFinder*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,1,0,G__get_linked_tagnum(&G__MCParticleFinderDictLN_TreeHandler),-1,-1,4,"fT=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"fnsig=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__MCParticleFinderDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarMCParticleFinderDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncMCParticleFinder(void) {
   /* MCParticleFinder */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__MCParticleFinderDictLN_MCParticleFinder));
   G__memfunc_setup("MCParticleFinder",1564,G__MCParticleFinderDict_496_0_1, 105, G__get_linked_tagnum(&G__MCParticleFinderDictLN_MCParticleFinder), -1, 0, 1, 1, 1, 0, "u 'TreeHandler' - 1 - in", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getMatchedMCId",1331,G__MCParticleFinderDict_496_0_2, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - recoId", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setNSig",701,G__MCParticleFinderDict_496_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - in", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__MCParticleFinderDict_496_0_4, 85, G__get_linked_tagnum(&G__MCParticleFinderDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&MCParticleFinder::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__MCParticleFinderDict_496_0_5, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MCParticleFinder::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__MCParticleFinderDict_496_0_6, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&MCParticleFinder::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__MCParticleFinderDict_496_0_7, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&MCParticleFinder::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__MCParticleFinderDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__MCParticleFinderDict_496_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__MCParticleFinderDict_496_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MCParticleFinder::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__MCParticleFinderDict_496_0_13, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&MCParticleFinder::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__MCParticleFinderDict_496_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MCParticleFinder::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__MCParticleFinderDict_496_0_15, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&MCParticleFinder::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("MCParticleFinder", 1564, G__MCParticleFinderDict_496_0_16, (int) ('i'), G__get_linked_tagnum(&G__MCParticleFinderDictLN_MCParticleFinder), -1, 0, 1, 1, 1, 0, "u 'MCParticleFinder' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~MCParticleFinder", 1690, G__MCParticleFinderDict_496_0_17, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncMCParticleFinderDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalMCParticleFinderDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcMCParticleFinderDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__MCParticleFinderDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__MCParticleFinderDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__MCParticleFinderDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__MCParticleFinderDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__MCParticleFinderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__MCParticleFinderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__MCParticleFinderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__MCParticleFinderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__MCParticleFinderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__MCParticleFinderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__MCParticleFinderDictLN_TreeHandler = { "TreeHandler" , 99 , -1 };
G__linked_taginfo G__MCParticleFinderDictLN_MCParticleFinder = { "MCParticleFinder" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableMCParticleFinderDict() {
  G__MCParticleFinderDictLN_TClass.tagnum = -1 ;
  G__MCParticleFinderDictLN_TBuffer.tagnum = -1 ;
  G__MCParticleFinderDictLN_TMemberInspector.tagnum = -1 ;
  G__MCParticleFinderDictLN_TObject.tagnum = -1 ;
  G__MCParticleFinderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__MCParticleFinderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__MCParticleFinderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__MCParticleFinderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__MCParticleFinderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__MCParticleFinderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__MCParticleFinderDictLN_TreeHandler.tagnum = -1 ;
  G__MCParticleFinderDictLN_MCParticleFinder.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableMCParticleFinderDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__MCParticleFinderDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__MCParticleFinderDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__MCParticleFinderDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__MCParticleFinderDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__MCParticleFinderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__MCParticleFinderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__MCParticleFinderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__MCParticleFinderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__MCParticleFinderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__MCParticleFinderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__MCParticleFinderDictLN_TreeHandler);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__MCParticleFinderDictLN_MCParticleFinder),sizeof(MCParticleFinder),-1,324608,(char*)NULL,G__setup_memvarMCParticleFinder,G__setup_memfuncMCParticleFinder);
}
extern "C" void G__cpp_setupMCParticleFinderDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupMCParticleFinderDict()");
  G__set_cpp_environmentMCParticleFinderDict();
  G__cpp_setup_tagtableMCParticleFinderDict();

  G__cpp_setup_inheritanceMCParticleFinderDict();

  G__cpp_setup_typetableMCParticleFinderDict();

  G__cpp_setup_memvarMCParticleFinderDict();

  G__cpp_setup_memfuncMCParticleFinderDict();
  G__cpp_setup_globalMCParticleFinderDict();
  G__cpp_setup_funcMCParticleFinderDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncMCParticleFinderDict();
  return;
}
class G__cpp_setup_initMCParticleFinderDict {
  public:
    G__cpp_setup_initMCParticleFinderDict() { G__add_setup_func("MCParticleFinderDict",(G__incsetup)(&G__cpp_setupMCParticleFinderDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initMCParticleFinderDict() { G__remove_setup_func("MCParticleFinderDict"); }
};
G__cpp_setup_initMCParticleFinderDict G__cpp_setup_initializerMCParticleFinderDict;

