/********************************************************************
* MCParticleFinderDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error MCParticleFinderDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMCParticleFinderDict();
extern void G__cpp_setup_inheritanceMCParticleFinderDict();
extern void G__cpp_setup_typetableMCParticleFinderDict();
extern void G__cpp_setup_memvarMCParticleFinderDict();
extern void G__cpp_setup_globalMCParticleFinderDict();
extern void G__cpp_setup_memfuncMCParticleFinderDict();
extern void G__cpp_setup_funcMCParticleFinderDict();
extern void G__set_cpp_environmentMCParticleFinderDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MCParticleFinder.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MCParticleFinderDictLN_TClass;
extern G__linked_taginfo G__MCParticleFinderDictLN_TBuffer;
extern G__linked_taginfo G__MCParticleFinderDictLN_TMemberInspector;
extern G__linked_taginfo G__MCParticleFinderDictLN_TObject;
extern G__linked_taginfo G__MCParticleFinderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MCParticleFinderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MCParticleFinderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__MCParticleFinderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MCParticleFinderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__MCParticleFinderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__MCParticleFinderDictLN_TreeHandler;
extern G__linked_taginfo G__MCParticleFinderDictLN_MCParticleFinder;

/* STUB derived class for protected member access */
